domain: podsmx.site
url: https://podsmx.site
baseurl: "/"

title: Pods MX 🇲🇽
email: wind@example.com
author: '@fakedad___'
author_url: https://www.instagram.com/fakedad___/

lang: es

plugins:
  - jekyll-seo-tag

color: "orange"
# disqus:
#   shortname: example-com
#
rrss:
  email: "example@example.cl"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
