domain: example.com
url: https://example.com
baseurl: "/wind"

title: Pods MX 🇲🇽
email: wind@example.com
author: Pods MX

lang: es

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "example@example.cl"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
